### ISSUE TITLE
Add Qiskit notebooks to `catalog_upload.json` files

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#218]
We added two Qiskit notebooks to the katalog repo but we still need to add/reference them in our bootstrapper and Quickstart and add them to the katalog README:

- [x] MLX bootstrapper and quickstart (#200)
- [ ] katalog repo landing page README (machine-learning-exchange/katalog#50)

**Related issues:**

- [x] machine-learning-exchange/katalog#36
- [x] #201
