### ISSUE TITLE
Update API to enable multi-user deployment

### ISSUE THREAD

**Issue by ckadner** [machine-learning-exchange/mlx#76]
Follow up to PR #59 

### TODOs:

* [ ] **upload** pipelines only by authenticated user:
  * [ ] without providing a `namespace` makes the pipeline public (**DEFAULT ?**)
  * [ ] with his/her `namespace` makes the pipeline private
* [ ] **launching** pipelines requires user's `namespace` (implicitly provided by UI, explicitly accepted by API)
* [ ] **listing** pipelines:
  * [ ] by `anonymous` user shows only public pipelines
  * [ ] by authenticated user shows his/her private pipelines and all public pipelines (API takes `namespace` parameter?)
* [ ] verify API deployment in cluster with Kubeflow Pipelines 1.5.0
* [ ] TODO: @Tomcli add MySQL policy back into demo cluster
